"""Editorial decisions after screening all 1,946 NL/RU/EN/POS rows.
These are model judgments, not an independent Dutch-language review.
Original Russian text is never overwritten.
"""
# A split proposal specifies distinct learning targets, not interchangeable answers.
SPLITS={
0:'appointment (umówione spotkanie/wizyta) | agreement (ustalenie/umowa); existing example selects appointment',
6:'surroundings/local area | environment or social setting',
14:'bill to pay (rachunek) | bank account (konto bankowe)',
35:'value/worth | monetary value; select a context before productive recall',
39:'opportunity | probability/chance',
41:'change something, transitive | change/become different, intransitive; auxiliary is construction-dependent',
53:'propose/suggest | introduce a person | zich voorstellen: imagine/introduce oneself',
59:'prepare something | zich voorbereiden op: prepare oneself for',
69:'zorgen voor: take care of/provide for | zorgen dat: ensure; store construction, not bare take care',
71:'voorkómen prevent (inseparable) | vóórkomen occur/be encountered (separable); different stress and forms',
94:'ordinary/usual, adjective | just/simply, adverb',95:'strange | foreign/unfamiliar',
140:'carry | wear clothing',150:'allow/let | leave something in a state/place',
151:'hold/keep | houden van: love/like; include van in the love construction',
164:'stab/prick | put/insert; bare put is too broad',171:'give as a gift | pour a drink',
173:'meet/encounter | hit/affect',200:'shine | seem/appear; select construction and auxiliary',
206:'float | drive/impel; distinguish transitivity and auxiliary',215:'smell/perceive odour | emit an odour',
226:'bake | fry; context must select cooking method',231:'man | husband',232:'woman | wife',
241:'female friend (koleżanka/przyjaciółka) | girlfriend/partner (dziewczyna/partnerka)',
261:'morgen tomorrow, adverb | de morgen morning, noun; do not mix noun meaning into tomorrow',
281:'road | way/route',285:'country | land/ground',329:'air | sky',342:'price (cena) | prize (nagroda)',
358:'long in space | long in time',378:'free/available | free/liberated; not automatically gratis',
379:'busy with work | crowded/bustling; noisy is not a safe standalone equivalent',
388:'learn/study | teach someone something; keep participants explicit',
415:'for a recipient/purpose | before/in front of',416:'of/possession | from/origin',
419:'over/above | about a topic',420:'through | by an agent/cause',428:'against | towards/by a time',
433:'inside | within a time limit',438:'just/recently | only/not until',441:'alone | only',
476:'thick | fat; label person-directed usage sensitively',484:'hard/solid | loud',
522:'pocket | bag/sack',529:'receipt | voucher/coupon',564:'map | card/postcard',
580:'rule | line of writing',586:'happiness | good luck',588:'care | worry/concern',
590:'sleep dream | aspiration',623:'dream during sleep | dream/aspire to',633:'miss a person | miss an event/connection',
644:'één one, numeral | een indefinite article; keep accent/weak-form policy explicit',
714:'heal/cure something | recover/get better; condition auxiliary by construction',
722:'carrot | plant root',738:'ice cream | ice',747:'drinking glass | glass material',
777:'leaf | sheet/page',790:'police officer | agent/representative',801:'row | queue',
819:'send | steer/drive',825:'borrow (from someone) | lend (to someone); require van/aan context',
846:'good-looking | clever/skilled',869:'spend money | publish',878:'share | divide',
888:'if | when; do not accept both blindly in every sentence',
893:'te too, degree adverb | te infinitive marker',895:'heel very, adverb | whole, adjective',
910:'fabric | substance | dust where selected separately',927:'a right/entitlement | law as system',
929:'voice | vote',949:'financial institution | seat/sofa/bench; choose sofa and institution as distinct pilot senses',
955:'sentence | meaning/sense; desire needs a separate zin hebben construction',
981:'thread | wire',997:'space | room/premises',1103:'crossing/act of crossing | resulting hybrid',
1145:'spicy | feisty; separate physical taste from personality',1154:'luck, noun | goodbye, interjection',
1196:'decrease | take/remove',1206:'look up information | visit a person',1208:'dress someone | zich aankleden: get dressed',
1264:'hang an object up | end a telephone call',1265:'answer a telephone | record audio/video',
1271:'babysit | be careful/watch out',1277:'keep records/up to date | keep pace with',
1285:'finish/complete | round a number',1309:'please in request | here you are when handing something over',
1310:'please, formal request | here you are, formal',1338:'intention/purpose | intended meaning',
1367:'short written note | banknote',1375:'digit | school grade',1386:'there, adverb | since/because, conjunction',
1397:'work shift/duty | service',1420:'even briefly/for a moment, adverb | even/equal, adjective; current RU describes wrong sense',
1421:'excuse/explanation | apology',1435:'function | job/role',1468:'gladly | polite request with graag',
1503:'marriage/being married | wedding event where attested; do not equate every occurrence with wedding',
1512:'jammer too bad/a pity, predicative | lament/misery, noun is a different use',
1616:'fingernail/toenail for body core | metal nail in supported contexts; common fastener spijker is missing',
1621:'male cousin | nephew',1626:'female cousin | niece',1634:'around | at a clock time',
1643:'research | examination/investigation',1656:'surgery | operation more generally',
1657:'charge battery | top up a balance',1752:'debt | guilt/blame',1781:'railway track | trace/trail',
1785:'continually/repeatedly | increasingly in steeds + comparative',1810:'technique | technology',
1840:'choose/select | investigate/sort out',1843:'school subject | compartment | profession as a later sense',
1870:'paint | dye',1922:'matter/case | business/shop',1924:'fail an examination | sink/drop',
1926:'she | they; stress and number-dependent agreement',1929:'de zegel postage/trading stamp | het zegel seal; article is sense-dependent'
}

FIX={
54:'Replace unconditional auxiliary zijn with context-scoped hebben/zijn. Preserve existing forms; do not mark zijn itself wrong.',
112:'POS=preposition (ondanks + noun phrase), not conjunction.',
113:'POS=adverb; daarom triggers main-clause inversion when fronted, not subordinate-clause order.',
114:'POS=adverb; add moreover/in addition context.',115:'POS=adverb, however.',
116:'POS=adverb; namely/you see/for depending on discourse context; use one explanatory example.',
119:'POS=adverb/particle; create contextual concessive or expectation-reversing sense, not a bag of synonyms.',
123:'Keep gekund but model the infinitive-for-participle construction with another infinitive separately; not every perfect uses gekund.',
124:'Missing perfect metadata is a gap, not a wrong form. Source gemoeten/hebben where appropriate; modal clusters require explicit IPP rules.',
125:'Missing perfect metadata is a gap. Source gemogen/hebben where appropriate; distinguish permission from possibility and modal clusters.',
127:'Do not invent a normal past participle for zullen. Mark not applicable/defective for this auxiliary use and describe zou/zouden separately.',
156:'Retain schiep/schiepen/geschapen for create. Do not replace with schepte/geschept belonging to scoop.',
161:'Retain later core with a concrete construction (e.g. in dienst treden); bare step is too broad for early productive recall.',
184:'Add sourced geklonken and appropriate perfect auxiliary for sound; keep riveting klinken separate.',
195:'Add sourced geleken/hebben if a perfect task is offered; distinguish seem from lijken op resemble.',
207:'Scope auxiliary to intended construction; do not make slash-separated auxiliary a context-free accepted answer.',
213:'Scope sluiten auxiliary to transitive close vs intransitive closure; preserve both attested possibilities with conditions.',
228:'EN=understand/hear what someone says (PL=rozumieć ze słuchu); retain distinction from begrijpen.',
244:'EN=family as household/parents and children; distinguish from familie relatives/extended family.',
245:'EN=family/relatives, often extended family; contrast with gezin household family.',
295:'Remove verb conjugation from noun het eten food. Link eating-verb forms to s160 only.',
300:'Use vegetable/vegetables with count and collective contexts; NL singular groente does not force singular Polish warzywo.',
492:'Verify POS by usage; gratis functions as adjective/adverb. Cost-free only, not available/liberated.',
573:'EN=teacher/instructor (including lecturer by context); lecturer alone is too narrow.',
615:'Use zich herinneren for remember; non-reflexive iemand herinneren aan means remind someone of.',
745:'EN=slice of bread, often with a topping; sandwich can imply two slices and is not a universal equivalent.',
800:'Keep het soort for category/kind and accept de soort where appropriate; biological species uses de. Do not auto-correct het to de.',
862:'For shaving oneself teach zich scheren; transitive scheren also exists. Add reflexive agreement.',
865:'EN=study, often at higher education; avoid an absolute university-only restriction.',
884:'EN=affirmative/corrective particle in a specific sentence (e.g. countering a negative); indeed alone is misleading.',
923:'EN=number/count of countable items; do not use unconstrained amount for mass nouns.',
1009:'EN=germination capacity/percentage under stated test conditions; distinguish capacity from speed of germination.',
1017:'Scope kweker as grower/raiser; breeder only in appropriate context, not an automatic synonym of veredelaar.',
1024:'EN=infestation/plague or a pest nuisance; an individual harmful organism is not always de plaag. Specify crop-infestation sense.',
1037:'EN=disinfection/decontamination; seed treatment is one application and can include non-disinfecting treatments.',
1049:'EN=disinfect/decontaminate; if treating seeds, state ontsmetten of seeds, not generic treatment.',
1084:'EN=lighting/illumination; supplementary lighting needs explicit bijbelichting or a scoped greenhouse context.',
1095:'Keep het rot for decay, confirmed by the selected noun sense; other rot homographs carry different articles. Do not replace from an unsensed union.',
1113:'Scope sample/specimen; monster creature is another sense that must not share prompts.',
1138:'Keep spuiten crop spraying in opt-in; common spray action can be added to core as a separately scoped sense.',
1149:'Canonical even; effe is informal spelling/variant. Retain only with register and variant link, never formal spelling target.',
1162:'Keep ordinary food core, regional preference tag; Northern NL is not a strict validity boundary.',
1166:'Lemma cent, plural centen used informally for money; preserve phrase sense and plural morphology, link s528.',
1197:'EN=take medicine in this sense (PL=zażywać lek), not the opaque take in.',
1204:'Use zich inschrijven for enrol/register oneself; separate enrolling another person. Preserve in + schrijven and reflexive spans.',
1248:'EN=true-breeding/pure-bred in specified organism context; crop variety purity is not automatically animal pedigree.',
1263:'Record uit + dunnen as separable even though legacy theme is agro.',
1289:'Use zich aanmelden for register/sign up oneself; separable aan + melden; separate announcing/registering another person.',
1300:'Use zich afmelden with context: report absence/cancel attendance or sign out of a service. RU выходить is too vague.',
1311:'EN=in advance/already, in anticipation; PL=z góry/już. In the meantime alone misleads.',
1316:'For RU отдельно choose adverb separately (PL=osobno); separate adjective is a related usage.',
1320:'Mark feminine assistant sense; do not infer all assistants are women.',
1337:'NL bedenken=think up/devise here; RU думать о is not equivalent. Proposed RU annotation придумать; preserve original.',
1343:'Remove RU со всех сторон from this sense; beide=both (PL=oba/obie).',
1350:'Treat get-well wish as formula (beterschap!/veel beterschap), linked to noun recovery; not an ordinary noun translation test.',
1365:'Scope uncontrolled fire/blaze; distinguish material/flame vuur.',
1369:'Noun foreign countries/foreign country; in het buitenland means abroad. Do not grade abroad as the bare noun form.',
1371:'Canonical lemma buur, plural buren. Retain plural people-reference sense and source article of singular.',
1378:'RU контакты plural broadens singular contact; scope contact/communication and number explicitly.',
1392:'Accept de deksel and het deksel for lid; legacy het is valid. Store both instead of claiming wrong gender.',
1404:'EN=turn/rotate; RU перевернуть fits a particular turn-over construction, not every draaien use.',
1406:'EN=drugstore retailer/shop, PL=drogeria/drogista; not a pharmacist dispensing prescriptions. Distinguish apotheker/apotheek.',
1408:'POS=verb, duren=last/take time; ov is wrong.',
1411:'RU снова is wrong for this intended sense. EN=once/sometime; PL=kiedyś/raz. Again belongs to weer/opnieuw.',
1429:'Noun final round/event (PL=finał); RU финальный is adjective and must be annotated as an error.',
1442:'EN=set of teeth/dentition; distinguish dentures by context rather than unqualified individual teeth.',
1450:'Preserve offensive original RU only in archive; use neutral PL=osoba z niepełnosprawnością / mający niepełnosprawność; label Dutch person-description usage.',
1458:'Getal is number, not unrestricted quantity; hoeveelheid is quantity.',
1471:'Informal sign-off, PL=pozdrawiam; RU с уважением suggests a more formal register.',
1473:'EN=entrance hall/large hall by context; university building is not a general equivalent.',
1479:'EN=signature; RU надпись is too broad and should not be a grading equivalent.',
1485:'Teach een heleboel as quantity expression (a lot); de heleboel as everything/all of it needs its own context.',
1501:'Noun help/assistance; RU помогать is a verb. Proposed annotation помощь; PL=pomoc.',
1510:'For adjective annual or adverb annually use matching POS/examples, not ov.',
1515:'POS=pronoun (jij), not adjective.',1519:'POS=possessive determiner/pronoun (jouw), not adjective.',
1537:'A task/job/chore, not necessarily daily; remove unsupported daily restriction.',
1539:'RU gloss unrelated/overbroad for spill/make a mess. PL=rozlewać/brudzić/robić bałagan; select one example.',
1553:'EN=quarter of an hour (15 minutes), PL=kwadrans; RU четверть alone is incomplete.',
1567:'Model lesgeven as separable/fixed lexical construction; preserve gaf les, lesgegeven and explicit spans.',
1598:'Map mensen as plural form of mens s243; no second independent concept for the identical people sense.',
1602:'EN=piece/item of furniture (countable), PL=mebel; RU мебель denotes furniture collectively.',
1610:'For feeling nauseous use PL=mdły/mieć nudności, RU тошнит; distinguish nausea-causing adjective sense.',
1639:'EN=maintenance/upkeep; RU ремонт is narrower repair, not a general equivalence.',
1664:'EN=consultation/discussion to coordinate, not any work meeting; compare vergadering.',
1699:'In Dutch grocery weights een pond is 500 g; distinguish from international pound (~454 g) in an explicit context.',
1702:'EN=postal delivery worker, PL=listonosz/listonoszka; RU почтовая служба is the service, not the worker.',
1716:'Keep school report/report card sense; add report/document separately later, not a blanket replacement.',
1723:'Adjective regular / adverb regularly; RU постоянно means constantly and overstates frequency.',
1727:'Noun respect (PL=szacunek), not verbs уважать/соблюдать.',
1737:'Keep het rooster; de is also attested in relevant uses. Store source-scoped variant, not an unconditional correction.',
1744:'For divorce, retain zijn and add scheiden van; generic separate transitive may take hebben, so scope the EN gloss.',
1766:'Smaken=have a taste/taste like (PL=smakować); RU пробовать belongs to proeven. Do not conflate active tasting with flavour.',
1768:'Snoep is confectionery/candy collectively, not necessarily one sweet; PL=słodycze.',
1776:'Speelgoed is toys/playthings collectively; do not require a singular toy equivalent.',
1777:'Playground, not a generic sports ground; annotate overbroad RU alternative.',
1780:'Jeans/trousers, not denim fabric; separate material spijkerstof.',
1786:'Wish of strength/support in difficulty, PL=trzymaj się/dużo siły; not general success-wish succes.',
1788:'Add sourced gestonken/hebben for stink; null fields are missing data.',
1803:'Store t/m as abbreviation variant of tot en met, preserving inclusive end-point meaning.',
1822:'Thuis=at home; naar huis=home as destination. Do not accept bare thuis for every English home cue.',
1829:'For intended by chance use adverbial toevallig; accidental/coincidental adjective requires separate grammatical contract.',
1831:'Noun total, PL=suma/całość; adjective overall and adverb altogether require separate POS/context.',
1853:'POS=verb, separable verder + gaan; current ov loses conjugation and spans.',
1863:'Gender-neutral nursing professional; PL=pielęgniarka/pielęgniarz; RU only feminine narrows it.',
1877:'EN=cardigan for current sense; RU жилет suggests sleeveless waistcoat. Verify garment context and label alternative senses.',
1881:'Adjective square (PL=kwadratowy), not noun area/площадь.',
1898:'Vriezen describes freezing weather/becoming frozen; making something freeze usually bevriezen/invriezen. Correct transitive RU замораживать.',
1911:'POS=interrogative determiner/pronoun, not adjective; welk/welke depends on noun number/article.',
1917:'Lemma werktijd with plural werktijden for working hours; preserve plural presentation and provenance.',
1940:'Source missing perfect form for eruitzien and construction eruit zien; do not derive by concatenating strings.',
1941:'Add source-confirmed geheten/hebben for be called if perfect tasks enabled.',
1942:'Negative-polarity need-to construction; source gehoeven/hebben and IPP conditions, never universal must.'
}
# False duplicates are kept as variants with identity aliases, not thrown away.
DROP={850:'Redundant inflected presentation of volgend (s1888), same next sense. Retire as separate teaching concept; retain source row and alias.',851:'Redundant inflected presentation of vorig (s1894), same previous sense. Retire separate concept; preserve legacy ID alias.'}
CORE_AGRO=set([1001,1004,1007,1011,1013,1014,1015,1020,1021,1025,1026,1027,1028,1029,1030,1031,1032,1033,1036,1038,1039,1040,1046,1050,1051,1063,1065,1066,1071,1074,1075,1076,1077,1080,1085,1087,1090,1091,1097,1102,1105,1106,1107,1108,1109,1113,1116,1117,1118,*range(1119,1136),1137,1217,1220,1221,1226,1229,1231,1232,1235,1238,1239,1240,1241,1246,1247,1252,1253,1257,1260])
CORE_SLANG={1139,1140,1144,1145,1146,1147,1148,1151,1152,1153,1156,1157,1158,1159,1162,1163,1164,1169,1173}
# Specific POS choices from the intended gloss, checked against dictionary observations.
POS={112:'prep',113:'adv',114:'adv',115:'adv',116:'adv',119:'adv',1408:'verb',1515:'pron',1519:'det',1504:'det',1853:'verb',1911:'det',1829:'adv'}
for n in list(range(643,674))+[674,675,676,1294,1314,1474,1607,1623,1823,1879,1883,1932,1933]:POS[n]='num'
for n in list(range(677,684))+[1318,1321,1390,1424,1513,1521,1523,1580,1594,1629,1633,1756]:POS[n]='noun'
for n in [404,405,457,458,459,460,461,1305,1306,1343,1393,1417,1487,1489,1490,1492,1505,1506,1518,1522,1605,1627,1646,1834,1907,1918,1926,1930]:POS[n]='pron'
for n in [410,455,456,462,463,883,1502,1592,1606,1608,1649,1841]:POS[n]='det'
for n in list(range(411,435))+[1342,1558,1614,1634,1680,1814,1844,1878]:POS[n]='prep'
for n in [406,407,408,409,1311,1312,1315,1316,1344,1354,1356,1386,1395,1399,1411,1412,1413,1414,1420,1440,1453,1468,1491,1507,1560,1572,1573,1589,1601,1615,1624,1637,1640,1648,1663,1667,1719,1720,1721,1785,1813,1822,1845,1846,1847,1848,1851,1872,1891,1899,1903,1910,1928]:POS[n]='adv'
for n in [1298,1348,1394,1415,1422,1441,1445,1456,1459,1461,1554,1565,1625,1654,1852,1861,1862,1869,1886,1897,1937]:POS[n]='adj'
for n in [1309,1310,1336,1350,1446,1448,1464,1465,1466,1471,1475,1495,1509,1512,1514,1571,1620,1632,1708,1773,1786,1912,1150,1152,1153,1155,1156,1157]:POS[n]='intj'
for n in [1527,1618,1674,1761]:POS[n]='name'
for n in [1510,1579,1909,1434,1645,1673]:POS[n]='adj' # usage may also be adverb; contract chooses one
POS[1419]='abbrev';POS[1803]='abbrev';POS[1934]='conj';POS[1696]='prep';POS[1307]='pron';POS[1308]='det';POS[1151]='particle'
