import collections,json,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];OLD=ROOT.parent/'woorden-research/docs/content';DOC=ROOT/'docs/content'
stats=json.load(open(ROOT/'evidence/audit-summary.json'));cov=json.load(open(ROOT/'evidence/core-coverage-summary.json'))
pilot=json.load(open(ROOT/'content/starter-pack.json'))['entries'];audit=json.load(open(ROOT/'content/legacy-audit-evidence.json'))
matrix=(OLD/'source-matrix.md').read_text()
matrix=matrix.replace('Not a grammar or translation authority.','The RBN-derived layer also contains useful explicit morphology: 29,621 distinct lemmas with de/het singular-article observations, 27,763 lexical entries with plural fields, 10,481 with auxiliary fields and 4,070 with separability fields. These are raw coverage counts, not correctness rates. Internal field conflicts exist; prefer explicit WordForms.article over inferred gender.')
matrix=matrix.replace('**Useful sense scaffold.** Retain provenance flags; never equate synset membership with interchangeable learner answers.','**Primary explicit-article cross-check and sense scaffold.** Select the RBN-derived record and preserve field lineage; use Kaikki for gaps and richer forms. Never equate synset membership with interchangeable learner answers.')
matrix=matrix.replace('**Reserve for targeted independent adjudication once a specific record is retrieved.** Not a bulk-import dependency in phase 1.','**Targeted independent adjudication.** ANW alsjeblieft was subsequently opened and supplies interjection classification; its page does not supply a full meaning profile. No verified bulk API.')
matrix=matrix.replace('and no entry-level adjudication is claimed from the landing pages alone.','and no entry-level adjudication follows from a landing page alone. A subsequent [ANW alsjeblieft entry](https://anw.ivdnt.org/article/alsjeblieft) was inspected for POS.')
insert='''| **Apertium Dutch** | Morphological paradigms, noun gender classes, separable-verb analysis | **Measured XML:** 25,272 active section entries / 20,248 distinct lemma strings; 13,475 noun strings in recognizable gender paradigms, 3,085 verb strings and 741 separable ones. Comments are excluded. The landbouw gender paradigm conflicts with ODWN/Kaikki; this is evidence that agreement must be tested, not assumed. | [Repository](https://github.com/apertium/apertium-nld); [XML dictionary](https://raw.githubusercontent.com/apertium/apertium-nld/master/apertium-nld.nld.dix). Keep paradigm IDs and generator/tool version if generating forms. | **Useful third project for candidate checks; not automatic tie-breaker.** Source lineage may overlap; paradigm decoding needs tests. |
| **Pattern Dutch** | Packaged conjugation table and morphology helpers | **Measured inspected Pattern3 table:** 3,709 rows / 3,673 distinct strings. Includes archaic werken forms wrocht/gewrocht. Package availability is not compatibility or modern-language QA. | [Project](https://github.com/clips/pattern); inspected Pattern3 source distribution, extracted Dutch verb table; package was not installed. | **Do not use as primary grammar truth.** Historical coverage/compatibility investigation only. |
| **UniMorph Dutch** | Feature-tagged inflection pairs | **Measured:** 55,467 data rows / 4,993 lemmas, including 2,844 adjective and 2,149 verb lemmas; no noun paradigms. Some very common verbs absent. | [Repository/TSV](https://github.com/unimorph/nld); [raw TSV](https://raw.githubusercontent.com/unimorph/nld/master/nld). | **Optional morphology test corpus.** Does not replace noun articles/plurals or comprehensive verb sources. |
| **FrequencyWords Dutch 2018** | Large raw subtitle surface counts | **Measured:** 1,107,145 strings, 263,017,508 token counts. Top 600 raw strings cover 77.315% of these counts, but forms, names and subtitle repetition make this unsuitable as a 600-sense comprehension claim. | [Repository](https://github.com/hermitdave/FrequencyWords); [NL full 2018](https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/nl/nl_full.txt), whitespace-delimited counts. | **Sensitivity check only.** SUBTLEX has more directly useful POS/lemma/CD information. |
| **Taaladvies / Onze Taal; targeted dictionary pages** | Specific article, grammatical and usage adjudication | Opened pages confirm de/het deksel and distinguish category soort from biological species. A live Wiktionary alsjeblieft page contains a sense absent from the old dump. | [Deksel](https://onzetaal.nl/taalloket/de-het-deksel), [soort](https://taaladvies.net/welk-of-welke-soort/), [live alsjeblieft](https://en.wiktionary.org/w/index.php?title=alsjeblieft&oldid=89632764). Record URL/revision, fact and retrieval date; no bulk availability claimed. | **Targeted adjudication; explicit overrides with evidence.** Never call every source disagreement a learner error. |
'''
matrix=matrix.replace('\n## Import traps found in real records','\n'+insert+'\n## Import traps found in real records')
matrix+='''\n## Job assignment after comparison\n\nRanking uses NT2Lex exposure plus SUBTLEX lemma/POS/CD and an explicit practical-utility policy. Grammar uses **ODWN explicit article fields plus Kaikki forms**, with Apertium/targeted language advice for adjudication. Tatoeba supplies example candidates; constrained original examples fill coverage gaps. EN glosses come primarily from the English Wiktionary edition; PL evidence comes from the Polish edition when the same sense exists, otherwise direct model-authored translation with independent review. No acquired resource provides a complete trustworthy NL–PL–EN A1–B2 deck.\n\nBulk measurements above were obtained in phase 1 and are retained in `evidence/source-inspection.json` and manifests. Two later local bulk copies (English Kaikki and Dutch-edition gzip) were incomplete; the delivery uses preserved, valid record excerpts rather than silently recounting partial files. Only complete JSON records from the valid English prefix supplied a few additional pilot headwords. Production imports must re-fetch and validate the full pinned files. The bundle contains the actual excerpt set used for the audit and pilot, not a claim that an incomplete local bulk copy is complete.\n'''
(DOC/'source-matrix.md').write_text(matrix)
curr=(OLD/'curriculum.md').read_text();curr=curr[:curr.index('## Representative starter fixture:')]
curr=curr.replace('draft v0.1','draft v0.2').replace('Phase 1','Research delivery').replace('phase 1','research delivery')
curr+='''## Representative starter fixture: 60 sense entries

`content/starter-pack.json` is the populated research fixture. Planning labels below map to issued UUIDs in `content/id-registry.json`; labels and ordering must never regenerate identity. This fixture deliberately includes a few A2 items and contrasting senses. It is not a promise to introduce all 60 immediately or a claim that all are language-reviewed.

| Ref | Dutch display | English sense | Polish meaning | Estimated band | Core situation |
|---|---|---|---|---|---|
'''
for e in pilot:
 a=e['lexeme']['morphology']['noun'];label=e['lexeme']['display']
 if a:label='/'.join(a['article']['accepted'])+' '+label
 curr+='| '+' | '.join([e['fixture_ref'],label,e['sense']['meanings']['en'][0],e['sense']['meanings']['pl'][0],e['cefr']['estimated'],e['curriculum']['themes'][0]])+' |\n'
curr+='''
Suggested first usable blocks: communication repair (ik, zijn, u, niet, begrijpen plus whole polite formulas); home descriptions (huis, deur, sleutel, open, klein/groot); shopping/payment (winkel, brood, water, geld, kopen, willen, betalen, pinnen); travel/time (gaan, komen, fiets, meenemen, hoe laat, op tijd); appointments/work/services (afspraak, huisarts, formulier, invullen); later contrast/grammar (omdat, gemeente, zich inschrijven, bank senses, deksel variants). Mix two to four targets from different POS rather than exhaust a semantic category. Introduce the second bank or alsjeblieft sense in a later context, not as a simultaneous translation list.

The examples are **fixture contexts**, not an automatically valid chronological course. A sentence can mention another target introduced later in this table. At introduction, supply reviewed support glosses; at independent testing, require the support words/forms and grammar to be known or scaffolded according to the task contract. A declared scaffold is not automatically mastered or free vocabulary. `example-prerequisites.json` records the actual footprint and `scaffold-glossary.json` distinguishes support units from the 60 scheduled sense targets. T43 disables unsupported example tasks rather than inventing an easier sentence at runtime. Past/perfect/subordinate-clause forms in the morphology inventory can be taught later than the headword.

## Frozen coverage baseline and its limits

The cumulative targets remain **600 A1, 1,500 A2, 3,000 B1, 5,000 B2 senses**: incremental additions 600 / 900 / 1,500 / 2,000. They are editorial planning budgets, not official CEFR requirements, not “words needed to pass”, and not empirically proven optima. Compare retention/workload and practical scenario completion before enlarging a band. Do not count every inflection or example as a new concept.

`core-target-candidates.json` freezes 5,000 explicit candidates (3,328 distinct headword strings), with 60 authored pilot senses and source-defined NT2Lex/ODWN candidates. It is a **provisional source-candidate baseline**. Remaining candidates are not fully reviewed for usefulness or CEFR. Rank components and imputations are visible: utility is a legacy-screening proxy or neutral default, and unassigned themes/prerequisites use neutral values. The production selector must replace these with recorded scenario judgments and recompute coverage as it fills blocks; its small implementation slices are in the task drafts. Do not publish this baseline as a ready 5,000-sense course.

Against that frozen baseline, 2,120 candidate senses have some legacy headword match and 2,880 do not. These are **headword-candidate counts**, not confirmed sense coverage: one legacy bank row cannot satisfy every source sense of bank. The missing-candidate CSV gives concrete source definitions for follow-up. 873 legacy lemma strings fall outside this provisional baseline; this does not by itself make them rare or unsuitable.

The 60-entry fixture has 10 headwords/formulas absent as standalone legacy entries: dank u wel, kunt u dat herhalen, geen probleem, hoe laat, op tijd, tot ziens, een afspraak maken, het spijt me, pinnen and half drie. Its sofa sense of bank and handing-over sense of alsjeblieft are also missing from the existing explicit glosses. Dutch-specific service/payment gaps are listed in `priority-gaps.csv`; they can override corpus rank once their sense and usage are sourced/reviewed. A named-service allowlist permits useful DigiD/BSN entries while proper-name noise remains excluded.

## Comparison decisions carried forward

Adopt the other model's emphasis on ODWN's RBN morphology, Apertium corroboration, explicit vocabulary/grammar prerequisites, reflexives, valid article variants and Dutch everyday service vocabulary. Keep the 600/1,500/3,000/5,000 sense budgets as policy; the alternative 600/2,000/3,500/5,000 is a calibration option, not established evidence. Reject unsupported coverage/accuracy percentages, first-attestation-as-CEFR rules, source-majority voting and Pattern-as-truth. See the preserved comparison memo for the exact checked claims.
'''
(DOC/'curriculum.md').write_text(curr)
shutil.copy2(OLD/'phase-1-comparison-and-merge-recommendations.md',DOC/'comparison-and-merge-decisions.md')
report=f'''# Woorden NG content recommendations

Use a **sense-based practical curriculum**, with source-backed grammar and externally reviewed EN/PL content. The original seed is useful raw material, but its sequence, coarse POS tags, polysemy and missing Polish/examples make it unsuitable as a finished course. Keep it immutable as provenance while building curated sense entries over it.

## Recommended decisions

1. Plan cumulative A1–B2 budgets of **600 / 1,500 / 3,000 / 5,000 senses**, subject to learner feedback. These are product choices, not official CEFR word requirements. Teach communication repair, home, shopping/payment and travel early; add useful local services even when subtitles undercount them. Farming and genuinely register-specific slang are opt-in.
2. Use **NT2Lex + SUBTLEX-NL** for level/frequency evidence, then practical utility and situation/prerequisite coverage for order. Keep source distributions, model CEFR estimates and curriculum stages separate. Frequency is not sense frequency and first attestation is not a CEFR label.
3. Use **ODWN's explicit article fields and Kaikki's noun/verb/IPA records** together. Add Apertium and targeted independent dictionary/language-advice checks for conflicts. Models write meanings, examples, translations and hints; they do not manufacture dictionary facts.
4. Use **Tatoeba as an example-candidate source**, not a pre-approved bilingual deck. The inspected export has 2,273 Dutch sentences with direct links to both EN and PL. That is too small and uneven to supply the whole curriculum. Directly authored NL examples with separate direct PL/EN translation fill gaps.
5. Replace the human-only review label with **field-level source status + actual different-vendor AI review + deterministic task eligibility**. The author cannot self-promote a draft by recording agreement. Preserve unresolved disagreements, hashes and review artifacts; do not claim an accuracy percentage from model agreement.
6. Prefer downloadable tested audio for predictable listening tasks; treat local Dutch TTS as a device-tested fallback. Source IPA is useful reference data, not proof of audio quality. No runtime AI integration is proposed.

## Audit result

Every original ID appears once in `legacy-audit.csv`: **1,268 keep, 554 fix, 122 move to opt-in, 2 drop-as-separate-concept**. “Keep” means retain the intended content as a core candidate; it does not mean publication-ready. Universal missing Polish/example/review work is reported separately so it does not obscure concrete errors. The two drops are redundant inflected presentations of volgend/vorig and retain ID aliases and archive text.

Of 191 agro-labelled entries, 85 are useful general/core candidates (vegetables, quality, packaging, infection etc.); 106 remain optional specialist agriculture. Of 35 slang-labelled entries, 19 are ordinary useful colloquial/food/social content, and 16 remain optional. These are explicit **editorial judgments**, not measured CEFR facts.

The machine pass found lemma-level article support for **988 of 1,005 noun-labelled rows**, with 17 lacking usable structured singular-article evidence. It did not establish a clear wrong de/het from these sources. In particular, het deksel and het soort must not be blanket-corrected. All **479 non-empty vt/vtp/vd surfaces** matched feature-filtered source forms; ten such fields were null. This does not validate auxiliary selection, sense association or whether the row is a verb. The noun het eten incorrectly carries the verb eten paradigm; zijn/hebben choices need construction-specific rules.

The editorial pass records 118 sense/construction split proposals and 113 individually written correction/qualification notes (sets overlap), plus POS/morphology/theme repairs. Examples: voorkomen combines distinct stress/morphology; zich herinneren and zich inschrijven need reflexives; rekening and bank need sense separation; Russian glosses for eens, even, smaken, hulp, respect and vierkant mislead or mismatch POS. All original Russian is preserved, with corrections as annotations.

## What is missing and what the counts mean

A frozen provisional 5,000-candidate denominator is included: **2,120 candidate senses have a legacy headword hit; 2,880 do not**. This is not 42.4% verified sense coverage. Non-pilot candidates still require semantic/usefulness review; generic source senses can be unsuitable even at a common headword. The 60-entry representative fixture has ten missing standalone headwords/formulas, plus missing meanings at already-present headwords. `priority-gaps.csv` adds concrete Dutch-life gaps such as DigiD, BSN, statiegeld, health-insurance terms and check-in/out vocabulary; those additions are proposed, not silently certified.

The seed begins with forty mostly abstract/general nouns and places the pronoun ik at s1506 and huisarts at s1499. Long blocks of irregular verbs, agriculture and alphabetic additions explain the poor introduction order more directly than a frequency score alone. Re-sequence by usable situations and prerequisites, while leaving the original index as provenance.

## Pilot and remaining gate

The delivered JSON contains **60 sense entries, 65 NL examples with EN/PL translations and exact answer spans**, noun articles/plurals/diminutives where applicable, 14 sourced verb inventories, sense-level metadata, field provenance and entry logs. **54 entries have source IPA; six do not.** Forms/IPA were extracted from inspected records. Examples/meanings/translations/CEFR estimates are model-authored judgments.

There is **no actual different-vendor review in this session**, and no tested audio asset. Consequently, **0/60 entries are eligible for curated publication** under the proposed policy. The review prompt, six source-linked request batches, response schema and hash-verification importer make that final review executable in Claude, but they are not a substitute for it. Source-backed morphology and structurally valid JSON must not be misrepresented as a finished reviewed deck. The ADR is a draft for repository adoption; no repository commit, PR or release was made.

## Sources actually inspected

The [source matrix](source-matrix.md) gives acquisition URLs, units, measured counts and access limits. Key opened sources: [NT2Lex paper](https://aclanthology.org/W18-0514/), [NT2Lex downloads](https://cental.uclouvain.be/cefrlex/nt2lex/download/), [SUBTLEX OSF file API](https://api.osf.io/v2/nodes/3d8cx/files/osfstorage/), [Kaikki raw data](https://kaikki.org/dictionary/rawdata.html), [Open Dutch WordNet](https://github.com/cltl/OpenDutchWordnet), [Apertium Dutch](https://github.com/apertium/apertium-nld), [OpenTaal](https://github.com/OpenTaal/opentaal-wordlist), [Tatoeba downloads](https://tatoeba.org/en/downloads), [Lingonaut Dutch announcement](https://lingonaut.app/blog/breton-dutch-and-qol-updates-wnwl-12), [CELEX catalogue](https://taalmaterialen.ivdnt.org/download/celex-2-nl/), [ANW alsjeblieft](https://anw.ivdnt.org/article/alsjeblieft), [de/het deksel](https://onzetaal.nl/taalloket/de-het-deksel), [soort](https://taaladvies.net/welk-of-welke-soort/), [DigiD explanation](https://www.digid.nl/en/about-digid/what-digid), [BSN explanation](https://www.government.nl/themes/government-and-democracy/personal-data/citizen-service-number-bsn), [Android Voice](https://developer.android.com/reference/android/speech/tts/Voice), [browser voice locality](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisVoice/localService), and [Piper](https://github.com/OHF-Voice/piper1-gpl).

Lingonaut had no verified machine-readable Dutch course export; CELEX required login and was not downloaded; concreteness data retrieval failed; no source-backed concreteness scores were used. The comparison memo records measured corrections to the other model's claims. All inspection is dated 3 October 2026; pinned manifests/excerpts let the team distinguish changing pages from the data actually used.
'''
(DOC/'research-report.md').write_text(report)
print('Wrote report, matrix and curriculum')
