#!/usr/bin/env bash
# Environment setup for cloud coding agents (Codex cloud "Install script", Claude Code cloud
# "Setup script"). Installs dependencies and a headless Chromium for the Playwright e2e tests.
# The Android SDK is intentionally NOT installed: CI builds the APK (see AGENTS.md).
set -euo pipefail

cd "$(dirname "$0")/.."

node_major="$(node -p 'process.versions.node.split(".")[0]')"
if (( node_major < 22 )); then
  echo "Node 22 or newer is required; the project uses Node 24 (.nvmrc). Found $(node --version)." >&2
  exit 1
fi

npm ci

# Browsers for the e2e tests: the builds that match this Playwright version, as in CI
# (package.json "config.playwrightBrowsers"). A pre-installed Chromium (PW_CHROMIUM_PATH) is only a
# fallback when the download fails: other versions can behave differently in tests.
read -r -a browsers <<<"$(node -p 'require("./package.json").config?.playwrightBrowsers ?? "chromium"')"
install=(npx playwright install)
if [[ "$(id -u)" == "0" ]]; then install+=(--with-deps); fi
if ! "${install[@]}" "${browsers[@]}"; then
  # Sandboxes often allow the npm registry but not Playwright's CDN: fetch the same Chromium major
  # from npm (@sparticuz/chromium) into .cache/npm-chromium/ and use it through a launcher script
  # that playwright.config.ts picks up. Other Chromium versions can fail tests that pass in CI.
  major="$(node -p 'JSON.parse(require("fs").readFileSync("node_modules/playwright-core/browsers.json","utf8")).browsers.find((b) => b.name === "chromium").browserVersion.split(".")[0]')"
  echo "Playwright's browser download failed; installing Chromium $major from npm instead." >&2
  dir="$PWD/.cache/npm-chromium"
  mkdir -p "$dir"
  if npm install --no-save --no-audit --no-fund --prefix "$dir" "@sparticuz/chromium@~${major}.0.0"; then
    cat >"$dir/chromium" <<LAUNCHER
#!/bin/sh
# Generated by scripts/agent-setup.sh: extracts the npm-hosted Chromium (into /tmp) when needed.
if [ ! -x /tmp/chromium ]; then
  (cd "$dir" && node --input-type=module -e "import c from '@sparticuz/chromium'; await c.executablePath();") >&2 || exit 1
fi
exec /tmp/chromium "\$@"
LAUNCHER
    chmod +x "$dir/chromium"
    "$dir/chromium" --version
    if [[ "${browsers[*]}" != "chromium" ]]; then
      echo "WARNING: only Chromium has an npm fallback; e2e projects for other browsers will fail here." >&2
    fi
  elif [[ -n "${PW_CHROMIUM_PATH:-}" ]]; then
    echo "WARNING: no matching Chromium available; e2e tests will use $PW_CHROMIUM_PATH." >&2
  else
    echo "Could not get a browser: allow cdn.playwright.dev and playwright.download.prss.microsoft.com, or the npm registry." >&2
    exit 1
  fi
fi

echo "Agent environment ready: npm run verify, npm run test:e2e"
